name: healthcare_yoga_app
description: A yoga teacher app for tracking students and payments
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.7.0
  razorpay_flutter: ^1.3.5
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
flutter:
  assets:
    - assets/icons/my_icon.png

